"""resume_filename replaced

Revision ID: 75a112a0acd2
Revises: fb4288661f27
Create Date: 2024-12-25 17:40:03.564985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a112a0acd2'
down_revision: Union[str, None] = 'fb4288661f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careersusers', sa.Column('resume_filename', sa.String(length=500), nullable=True))
    op.drop_column('careersusers', 'resume_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careersusers', sa.Column('resume_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('careersusers', 'resume_filename')
    # ### end Alembic commands ###
