"""production Initial migration

Revision ID: fb6acab01178
Revises: 
Create Date: 2024-12-26 13:32:12.667745+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6acab01178'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careersusers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.String(length=150), nullable=True),
    sa.Column('resume_filename', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_careersusers_email'), 'careersusers', ['email'], unique=True)
    op.create_index(op.f('ix_careersusers_mobile'), 'careersusers', ['mobile'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_careersusers_mobile'), table_name='careersusers')
    op.drop_index(op.f('ix_careersusers_email'), table_name='careersusers')
    op.drop_table('careersusers')
    # ### end Alembic commands ###
